### ISSUE TITLE
go get gives rise to 'undefined reference to symbol 'zhash_cursor' '

### ISSUE THREAD

**Issue by pietercardoen** [zeromq/gozyre#11]
When executing

go get -u github.com/zeromq/gozyre

I get these error log:

\# github.com/zeromq/gozyre
/usr/bin/ld: $WORK/b001/_x003.o: undefined reference to symbol 'zhash_cursor'
//usr/local/lib/libczmq.so.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
\# github.com/zeromq/gozyre
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/options.go: In function ‘_zyre_set_header’:
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/options.go:10:2: warning: format not a string literal and no format arguments [-Wformat-security]
 // zyre_set_header(self, group, value);
  ^
\# github.com/zeromq/gozyre
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/zyre.go: In function ‘_zyre_set_endpoint’:
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/zyre.go:10:3: warning: format not a string literal and no format arguments [-Wformat-security]
 //  return zyre_set_endpoint(self, e);
   ^
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/zyre.go: In function ‘_zyre_gossip_bind’:
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/zyre.go:13:3: warning: format not a string literal and no format arguments [-Wformat-security]
 //  zyre_gossip_bind(self, e);
   ^
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/zyre.go: In function ‘_zyre_gossip_connect’:
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/zyre.go:16:3: warning: format not a string literal and no format arguments [-Wformat-security]
 //  zyre_gossip_connect(self, e);
   ^
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/zyre.go: In function ‘_zyre_whispers’:
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/zyre.go:19:2: warning: format not a string literal and no format arguments [-Wformat-security]
 // return zyre_whispers(self, peer, s);
  ^
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/zyre.go: In function ‘_zyre_shouts’:
../../../golang/httpserver/packages/src/github.com/zeromq/gozyre/zyre.go:22:2: warning: format not a string literal and no format arguments [-Wformat-security]
 // return zyre_shouts(self, group, value);

What can I do to fix this?

Thanks.

**Comment by pietercardoen** [comment]
Apparently, it can be fixed by adding this in zyre.go:
//#cgo pkg-config: libzmq
//#cgo pkg-config: libczmq
above line:
//#cgo pkg-config: libzyre

Will create a pull request

**Comment by vyskocilm** [comment]
Awesome! Thanks for the contribution!
