### ISSUE TITLE
Missing GO API for SetBeaconPeerPort()

### ISSUE THREAD

**Issue by stephan57160** [zeromq/gozyre#13]
# Issue description
On Linux, the Beacon Peer Port is randomly chosen from 49152 to ... 60000.
Because of that, it might be painful to configure firewalls with such kind of port (especially, when we want Zero Configuration).

See also ZYRE issues #323 and #594, for the full story.

# Solution
Add SetBeaconPeerPort(), calling zyre_set_beacon_peer_port(), like it's done for some other functions.

# Patch & pull request.
Patch available, for review.
Pull request in progress.

**Comment by vyskocilm** [comment]
Thanks for contributing.

**Comment by vyskocilm** [comment]
@stephan57160 please note that I have hidden the draft API support behind `draft` build tag, so one must type `go build -tags=draft` in order to have an access to `DRAFT` methods of zyre. I updated CircleCI setup, so both builds are now tested via CI.

**Comment by stephan57160** [comment]
Oh. Was wondering how to play with drafs at that time.
Thx.
