### ISSUE TITLE
Circle CI does pass results to zeromq/gozyre pull requests

### ISSUE THREAD

**Issue by vyskocilm** [zeromq/gozyre#9]
While I can get the workflow results when looking to CircleCI dashoboard, results are NOT available in Pull Request screens. And this is cumbersome. I tried to setup zeromq/gozyre project in CircleCI, but it looks I do not have enough permissions to do so. I got 403 for the project setting page.

The problem lives in CircleCI and then someone (@trevorbernard adds support for jeromq) must grant me the permissions.

Either it's a problem of zeromq and github permissons - in that case @bluca would be able to fix it.

Thanks for help.

**Comment by bluca** [comment]
I've invited you to the team, try again

**Comment by vyskocilm** [comment]
OK, I got an invitation and can access the setup screen. Thanks!
